TAG_MAP = {
    'index': {
        'doxygenindex': 'DoxygenIndex',
        'compound': 'Compound',
        'member': 'Member'
    },
    'compound': {
        'briefdescription': 'Description',
        'codeline': 'CodeLine',
        'compounddef': 'CompoundDef',
        'compoundref': 'CompoundRef',
        'description': 'Description',
        'detaileddescription': 'Description',
        'docanchor': 'DocAnchor',
        'docblockquote': 'DocBlockQuote',
        'doccaption': 'DocCaption',
        'doccopy': 'DocCopy',
        'docemoji': 'DocEmoji',
        'docentry': 'DocEntry',
        'docformula': 'DocFormula',
        'docheading': 'DocHeading',
        'dochtmlonly': 'DocHtmlOnly',
        'docimage': 'DocImage',
        'docindexentry': 'DocIndexEntry',
        'docinternal': 'DocInternal',
        'doclanguage': 'DocLanguage',
        'doclist': 'DocList',
        'docmarkup': 'DocMarkup',
        'docpara': 'DocPara',
        'docparamlist': 'DocParamList',
        'docparamlistitem': 'DocParamListItem',
        'docparamname': 'DocParamName',
        'docparamnamelist': 'DocParamNameList',
        'docparblock': 'DocParBlock',
        'docreftext': 'DocRefText',
        'docrow': 'DocRow',
        'docsect1': 'DocSect1',
        'docsect2': 'DocSect2',
        'docsect3': 'DocSect3',
        'docsimplesect': 'DocSimpleSect',
        'doctable': 'DocTable',
        'doctitle': 'DocTitle',
        'doctocitem': 'DocTocItem',
        'doctoclist': 'DocTocList',
        'doctsect4': 'DocSect4',
        'docurllink': 'DocUrlLink',
        'docvariablelist': 'DocVariableList',
        'docvarlistentry': 'DocVarListEntry',
        'docxrefsect': 'DocXrefSect',
        'doxygen': 'Doxygen',
        'enumvalue': 'EnumValue',
        'highlight': 'Highlight',
        'inc': 'Inc',
        'innerclass': 'InnerClass',
        'linkedtext': 'LinkedText',
        'listing': 'Listing',
        'location': 'Location',
        'memberdef': 'MemberDef',
        'param': 'Param',
        'para': 'DocPara',
        'ref': 'Ref',
        'reftext': 'RefText',
        'reimplement': 'Reimplement',
        'sectiondef': 'SectionDef',
        'sp': 'Sp',
        'templateparamlist': 'TemplateParamList'
    }
}

for xsd_name, xsd in TAG_MAP.items():
    for tag, class_name in xsd.items():
        TAG_MAP[xsd_name][tag] = '.'.join([
            'doxyparser',
            xsd_name,
            'types',
            class_name.lower(),
            class_name
        ])
